version: '2'
services:
  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget
    restart: always
    ports:
      - 6789:6789
    environment:
      - TZ=GB
      - PUID=0
      - PGID=0
    volumes:
      - /config/nzbget:/config
      - /storage:/storage
      - /downloads:/downloads
      - /etc/hosts:/etc/hosts
    labels:
      - "traefik.enable=true"
      - "traefik.port=6789"
      - "traefik.protocol=http"
      - "traefik.frontend.rule=Host:bastion76.com"
      - "traefik.frontend.rule=PathPrefix:/nzbget/,/nzbget"
      - "traefik.frontend.auth.basic.usersFile=/config/.htpasswd"

  plexmediaserver:
    container_name: plexmediaserver
    image: linuxserver/plex
    restart: always
    network_mode: host
    environment:
      - TZ=GB
      - VERSION=lastest
      - PUID=0
      - PGID=0
    volumes:
      - /config/plexmediaserver:/config
      - /storage/0/TV_Shows:/data/tvshows
      - /storage/0/Videos:/data/movies
      - /storage/0/Audio:/data/music
      - /storage/0/JW:/data/JW
      - /storage/0/tvheadend/dvr-dad:/data/tvrecordings
      - /storage/0/tvheadend/F1:/data/F1
      - /tmp:/tmp
      - /etc/hosts:/etc/hosts
    devices:
      - /dev/dri:/dev/dri

  traefik:
    container_name: traefik
    image: traefik:alpine
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /config/traefik:/config
      - /config/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /config/traefik/acme.json:/acme.json
      - /etc/hosts:/etc/hosts

  tautulli:
    container_name: tautulli
    image: linuxserver/tautulli
    restart: always
    depends_on:
      - plexmediaserver
    ports:
      - "8181:8181"
    environment:
      - TZ=GB
      - PUID=0
      - PGID=0
    volumes:
      - /config/tautulli:/config
      - /config/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
      - /etc/hosts:/etc/hosts
    labels:
      - "traefik.enable=true"
      - "traefik.port=8181"
      - "traefik.protocol=http"
      - "traefik.frontend.rule=Host:bastion76.com"
      - "traefik.frontend.rule=PathPrefix:/plexpy/,/plexpy,/plexpy/home"
      - "traefik.frontend.auth.basic.usersFile=/config/.htpasswd"

  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    ports:
      - "9999:9000"
    environment:
      - TZ=GB
      - PUID=0
      - PGID=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/hosts:/etc/hosts
    labels:
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "traefik.protocol=http"
      - "traefik.frontend.rule=Host:bastion76.com"
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.frontend.auth.basic.usersFile=/config/.htpasswd"
    command: --no-auth

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:preview
    restart: always
    depends_on:
      - hydra2
      - nzbget
    ports:
      - "8989:8989"
    environment:
      - TZ=GB
      - PUID=0
      - PGID=0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /config/sonarr:/config
      - /storage/0/TV_Shows:/tv
      - /downloads:/downloads
      - /etc/hosts:/etc/hosts
    labels:
      - "traefik.enable=true"
      - "traefik.port=8989"
      - "traefik.protocol=http"
      - "traefik.frontend.rule=Host:bastion76.com"
      - "traefik.frontend.rule=PathPrefix:/sonarr/,/sonarr"
      - "traefik.frontend.auth.basic.usersFile=/config/.htpasswd"

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: always
    depends_on:
      - hydra2
      - nzbget
    ports:
      - "7878:7878"
    environment:
      - TZ=GB
      - PUID=0
      - PGID=0
    volumes:
      - /etc/localtime:/etc/localtime:ro 
      - /config/radarr:/config 
      - /storage/0/Videos:/movies 
      - /downloads:/downloads 
      - /etc/hosts:/etc/hosts
    labels:
      - "traefik.enable=true"
      - "traefik.port=7878"
      - "traefik.protocol=http"
      - "traefik.frontend.rule=Host:bastion76.com"
      - "traefik.frontend.rule=PathPrefix:/radarr/,/radarr"
      - "traefik.frontend.auth.basic.usersFile=/config/.htpasswd"

  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr
    restart: always
    depends_on:
      - hydra2
      - nzbget
    ports:
      - "8686:8686"
    environment:
      - TZ=GB
      - PUID=0
      - PGID=0
    volumes:
      - /etc/localtime:/etc/localtime:ro 
      - /config/lidarr:/config 
      - /storage/0/lidarr-music:/music
      - /downloads:/downloads 
      - /etc/hosts:/etc/hosts
    labels:
      - "traefik.enable=true"
      - "traefik.port=8686"
      - "traefik.protocol=http"
      - "traefik.frontend.rule=Host:bastion76.com"
      - "traefik.frontend.rule=PathPrefix:/lidarr/,/lidarr"
      - "traefik.frontend.auth.basic.usersFile=/config/.htpasswd"

  tvheadend:
    container_name: tvheadend
    image: linuxserver/tvheadend
    restart: always
    network_mode: host
    environment:
      - TZ=GB
      - PUID=44
      - PGID=128
    volumes:
      - /config/tvheadend:/config
      - /storage/0/tvheadend:/recordings
      - /etc/hosts:/etc/hosts
    devices:
      - "/dev/dri:/dev/dri"


#  watchtower:
#    container_name: watchtower
#    image: v2tec/watchtower
#    restart: always
#    command: --cleanup
#    network_mode: host
#    environment:
#      - TZ=GB
#      - PUID=0
#      - PGID=0
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock

#  timecapsule:
#    container_name: timecapsule
#    image: pdouble16/timecapsule
#    restart: always
#    ports:
#      - "548:548"
#    environment:
#      - TZ=GB
#      - PUID=0
#      - PGID=0
#      - VERSION=latest
#      - VOLSIZELIMIT=256000
#    volumes:
#      - /storage/0/timecapsule/backup:/backup

#  desktop:
#    container_name: desktop
#    image: consol/centos-xfce-vnc
#    ports:
#      - "5901:5901"
#      - "6901:6901"
#    volumes:
#      - /storage:/storage

  hydra2:
    container_name: hydra2
    image: linuxserver/hydra2
    restart: always
    ports:
      - "5076:5076"
    environment:
      - TZ=GB
      - PUID=0
      - PGID=0
    volumes:
      - /config/hydra2:/config
      - /downloads:/downloads
      - /etc/hosts:/etc/hosts
